+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf '/tmp/point*'
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the database config.'
+ message='Start to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the database config.'
Fri Aug 11 01:04:41 2023 - INFO  - Start to prepare the database config.
+ cur_lang=en_US.UTF-8
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
++ date +%Y%m%d%H%M%S
+ cur_date=20230811010441
++ CREATE_VG
+++ date +%Y%m%d%H%M%S
++ cur_date=20230811010441
+++ grep disk
+++ lsblk
+++ awk '{print $1}'
+++ tail -n 1
++ free_disk=vdt
++ disk_name=/dev/vdt
++ pvcreate /dev/vdt -f
++ [[ 5 -eq 0 ]]
+++ pvcreate /dev/vdt
+++ grep test_vggroup
+++ cut -d '"' -f 4
++ vggroup=test_vggroup20230811002108
++ printf test_vggroup20230811002108
+ vggroup=test_vggroup20230811002108
+ lv1=test_lv120230811010441
+ lv2=test_lv220230811010441
+ lv3=test_lv320230811010441
+ lvcreate -n test_lv120230811010441 -L 2G test_vggroup20230811002108 -y
  Volume group "test_vggroup20230811002108" has insufficient free space (124 extents): 512 required.
+ lvcreate -n test_lv220230811010441 -L 2G test_vggroup20230811002108 -y
  Volume group "test_vggroup20230811002108" has insufficient free space (124 extents): 512 required.
+ lvcreate -n test_lv320230811010441 -L 2G test_vggroup20230811002108 -y
  Volume group "test_vggroup20230811002108" has insufficient free space (124 extents): 512 required.
+ mkfs.ext3 /dev/test_vggroup20230811002108/test_lv120230811010441
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/test_vggroup20230811002108/test_lv120230811010441 does not exist and no size was specified.
+ mkfs.ext4 /dev/test_vggroup20230811002108/test_lv220230811010441
mke2fs 1.47.0 (5-Feb-2023)
The file /dev/test_vggroup20230811002108/test_lv220230811010441 does not exist and no size was specified.
+ mkfs.xfs /dev/test_vggroup20230811002108/test_lv320230811010441
oe_test_FSIO_mount_character_dir.sh: line 35: mkfs.xfs: command not found
+ charc=/mnt/testc20230811010441
+ mknod /mnt/testc20230811010441 c 1 1
+ LOG_INFO 'Finish to prepare the database config.'
+ message='Finish to prepare the database config.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Finish to prepare the database config.'
Fri Aug 11 01:04:46 2023 - INFO  - Finish to prepare the database config.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Aug 11 01:04:48 2023 - INFO  - Start to run test.
+ mount /dev/test_vggroup20230811002108/test_lv120230811010441 /mnt/testc20230811010441
+ grep 'mount point is not a directory'
+ CHECK_RESULT 1 0 0 'mount ext3 on character block unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='mount ext3 on character block unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'mount ext3 on character block unexpectly.'
+ LOG_ERROR 'mount ext3 on character block unexpectly.'
+ message='mount ext3 on character block unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mount ext3 on character block unexpectly.'
Fri Aug 11 01:04:49 2023 - ERROR - mount ext3 on character block unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_character_dir.sh line 44'
+ message='oe_test_FSIO_mount_character_dir.sh line 44'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_character_dir.sh line 44'
Fri Aug 11 01:04:51 2023 - ERROR - oe_test_FSIO_mount_character_dir.sh line 44
+ '[' 0 -eq 1 ']'
+ return 0
+ mount /dev/test_vggroup20230811002108/test_lv220230811010441 /mnt/testc20230811010441
+ grep 'mount point is not a directory'
+ CHECK_RESULT 1 0 0 'mount ext4 on character block unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='mount ext4 on character block unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'mount ext4 on character block unexpectly.'
+ LOG_ERROR 'mount ext4 on character block unexpectly.'
+ message='mount ext4 on character block unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mount ext4 on character block unexpectly.'
Fri Aug 11 01:04:52 2023 - ERROR - mount ext4 on character block unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_character_dir.sh line 46'
+ message='oe_test_FSIO_mount_character_dir.sh line 46'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_character_dir.sh line 46'
Fri Aug 11 01:04:53 2023 - ERROR - oe_test_FSIO_mount_character_dir.sh line 46
+ '[' 0 -eq 1 ']'
+ return 0
+ mount /dev/test_vggroup20230811002108/test_lv320230811010441 /mnt/testc20230811010441
+ grep 'mount point is not a directory'
+ CHECK_RESULT 1 0 0 'mount xfs on character block unexpectly.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='mount xfs on character block unexpectly.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'mount xfs on character block unexpectly.'
+ LOG_ERROR 'mount xfs on character block unexpectly.'
+ message='mount xfs on character block unexpectly.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'mount xfs on character block unexpectly.'
Fri Aug 11 01:04:55 2023 - ERROR - mount xfs on character block unexpectly.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_mount_character_dir.sh line 48'
+ message='oe_test_FSIO_mount_character_dir.sh line 48'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_mount_character_dir.sh line 48'
Fri Aug 11 01:04:56 2023 - ERROR - oe_test_FSIO_mount_character_dir.sh line 48
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Aug 11 01:04:57 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 3
+ test 3 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Aug 11 01:04:58 2023 - ERROR - failed to execute the case.
+ exit 3
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Aug 11 01:04:59 2023 - INFO  - Start to restore the test environment.
+ rm -rf /mnt/testc20230811010441
+ DELETE_LV /dev/test_vggroup20230811002108/test_lv120230811010441
+ lvname=/dev/test_vggroup20230811002108/test_lv120230811010441
+ lvremove /dev/test_vggroup20230811002108/test_lv120230811010441 -y
  Failed to find logical volume "test_vggroup20230811002108/test_lv120230811010441"
+ DELETE_LV /dev/test_vggroup20230811002108/test_lv220230811010441
+ lvname=/dev/test_vggroup20230811002108/test_lv220230811010441
+ lvremove /dev/test_vggroup20230811002108/test_lv220230811010441 -y
  Failed to find logical volume "test_vggroup20230811002108/test_lv220230811010441"
+ DELETE_LV /dev/test_vggroup20230811002108/test_lv320230811010441
+ lvname=/dev/test_vggroup20230811002108/test_lv320230811010441
+ lvremove /dev/test_vggroup20230811002108/test_lv320230811010441 -y
  Failed to find logical volume "test_vggroup20230811002108/test_lv320230811010441"
+ export LANG=en_US.UTF-8
+ LANG=en_US.UTF-8
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Aug 11 01:05:02 2023 - INFO  - End to restore the test environment.
