+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Sep 12 10:04:28 2023 - INFO  - Start environment preparation.
+ point_list=($(CREATE_FS))
++ CREATE_FS
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230912100428
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230912100428
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdt
+++ disk_name=/dev/vdt
+++ pvcreate /dev/vdt -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vdt
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230912100428
++ point=/tmp/point120230912100428
++ lvcreate -n test_lv120230912100428 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230912100428
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230912100428 does not exist and no size was specified.
++ mkdir /tmp/point120230912100428
++ mount /dev//test_lv120230912100428 /tmp/point120230912100428
mount: /tmp/point120230912100428: special device /dev//test_lv120230912100428 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100428 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230912100428
++ point=/tmp/point220230912100428
++ lvcreate -n test_lv220230912100428 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230912100428
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv220230912100428 does not exist and no size was specified.
++ mkdir /tmp/point220230912100428
++ mount /dev//test_lv220230912100428 /tmp/point220230912100428
mount: /tmp/point220230912100428: special device /dev//test_lv220230912100428 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100428 /tmp/point220230912100428 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230912100428
++ point=/tmp/point320230912100428
++ lvcreate -n test_lv320230912100428 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230912100428
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230912100428
++ mount /dev//test_lv320230912100428 /tmp/point320230912100428
mount: /tmp/point320230912100428: special device /dev//test_lv320230912100428 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428 '
++ count=4
++ echo /tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Sep 12 10:04:29 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Sep 12 10:04:29 2023 - INFO  - Start to run test.
++ seq 1 2
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point220230912100428
+ echo test
+ mv /tmp/point220230912100428/testfile1
+ grep 'missing destination file operand'
mv: missing destination file operand after '/tmp/point220230912100428/testfile1'
+ CHECK_RESULT 0 0 0 'The cmd lacks parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The cmd lacks parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point220230912100428/testfile1 /tmp/point220230912100428/testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
+ grep 'File name too long'
mv: cannot stat '/tmp/point220230912100428/testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa': File name too long
+ CHECK_RESULT 0 0 0 'File can be moved when length of file name is more than 255 on /tmp/point220230912100428.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='File can be moved when length of file name is more than 255 on /tmp/point220230912100428.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point220230912100428/testfile1 /tmp/point220230912100428/testfile2 /tmp/point220230912100428/testfile3
+ grep 'is not a directory'
+ CHECK_RESULT 1 0 0 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ LOG_ERROR 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ message='The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.'
Tue Sep 12 10:04:29 2023 - ERROR - The cmd with blank space parameter was executed succeed on unexpect on /tmp/point220230912100428.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_rename_file_fail.sh line 37'
+ message='oe_test_FSIO_rename_file_fail.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_rename_file_fail.sh line 37'
Tue Sep 12 10:04:29 2023 - ERROR - oe_test_FSIO_rename_file_fail.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ mv /tmp/point220230912100428/testfile1 /tmp/point220230912100428/a:1 /tmp/point220230912100428/b:2
+ grep 'is not a directory'
+ CHECK_RESULT 1 0 0 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ LOG_ERROR 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ message='The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.'
Tue Sep 12 10:04:29 2023 - ERROR - The cmd with dict parameter was executed succeed on unexpect on /tmp/point220230912100428.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_rename_file_fail.sh line 39'
+ message='oe_test_FSIO_rename_file_fail.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_rename_file_fail.sh line 39'
Tue Sep 12 10:04:29 2023 - ERROR - oe_test_FSIO_rename_file_fail.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ for i in $(seq 1 $((${#point_list[@]} - 1)))
+ var=/tmp/point320230912100428
+ echo test
+ mv /tmp/point320230912100428/testfile1
+ grep 'missing destination file operand'
mv: missing destination file operand after '/tmp/point320230912100428/testfile1'
+ CHECK_RESULT 0 0 0 'The cmd lacks parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='The cmd lacks parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point320230912100428/testfile1 /tmp/point320230912100428/testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
+ grep 'File name too long'
mv: cannot stat '/tmp/point320230912100428/testaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa': File name too long
+ CHECK_RESULT 0 0 0 'File can be moved when length of file name is more than 255 on /tmp/point320230912100428.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='File can be moved when length of file name is more than 255 on /tmp/point320230912100428.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ mv /tmp/point320230912100428/testfile1 /tmp/point320230912100428/testfile2 /tmp/point320230912100428/testfile3
+ grep 'is not a directory'
+ CHECK_RESULT 1 0 0 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ LOG_ERROR 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ message='The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.'
Tue Sep 12 10:04:29 2023 - ERROR - The cmd with blank space parameter was executed succeed on unexpect on /tmp/point320230912100428.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_rename_file_fail.sh line 37'
+ message='oe_test_FSIO_rename_file_fail.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_rename_file_fail.sh line 37'
Tue Sep 12 10:04:29 2023 - ERROR - oe_test_FSIO_rename_file_fail.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ mv /tmp/point320230912100428/testfile1 /tmp/point320230912100428/a:1 /tmp/point320230912100428/b:2
+ grep 'is not a directory'
+ CHECK_RESULT 1 0 0 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ LOG_ERROR 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ message='The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.'
Tue Sep 12 10:04:29 2023 - ERROR - The cmd with dict parameter was executed succeed on unexpect on /tmp/point320230912100428.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_rename_file_fail.sh line 39'
+ message='oe_test_FSIO_rename_file_fail.sh line 39'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_rename_file_fail.sh line 39'
Tue Sep 12 10:04:29 2023 - ERROR - oe_test_FSIO_rename_file_fail.sh line 39
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Sep 12 10:04:29 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Sep 12 10:04:29 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Sep 12 10:04:29 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428
+ list='/tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428'
+ REMOVE_FS '/tmp/point120230912100428 /tmp/point220230912100428 /tmp/point320230912100428'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230912100428
++ df -T
++ grep /tmp/point120230912100428
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230912100428
++ df -T
++ grep /tmp/point220230912100428
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230912100428
++ df -T
++ grep /tmp/point320230912100428
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Sep 12 10:04:29 2023 - INFO  - End to restore the test environment.
