+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Tue Sep 12 10:28:10 2023 - INFO  - Start to prepare the test environment.
+ echo '-w /etc/passwd -p wa -k passwd_changes'
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Tue Sep 12 10:28:10 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Sep 12 10:28:10 2023 - INFO  - Start to run test.
+ service auditd restart
Redirecting to /bin/systemctl restart auditd.service
Failed to restart auditd.service: Unit auditd.service not found.
+ auditctl -D
oe_test_audit_rule_fetch_from_rule.sh: line 33: auditctl: command not found
+ CHECK_RESULT 127 0 0 'delete failed'
+ actual_result=127
+ expect_result=0
+ mode=0
+ error_log='delete failed'
+ exit_mode=0
+ '[' -z 127 ']'
+ '[' 0 -eq 0 ']'
+ test 127x '!=' 0x
+ test -n 'delete failed'
+ LOG_ERROR 'delete failed'
+ message='delete failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'delete failed'
Tue Sep 12 10:28:10 2023 - ERROR - delete failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_rule_fetch_from_rule.sh line 34'
+ message='oe_test_audit_rule_fetch_from_rule.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_rule_fetch_from_rule.sh line 34'
Tue Sep 12 10:28:10 2023 - ERROR - oe_test_audit_rule_fetch_from_rule.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ auditctl -R /opt/test.rules
oe_test_audit_rule_fetch_from_rule.sh: line 35: auditctl: command not found
+ auditctl -l
+ grep -e '-w /etc/passwd -p wa -k passwd_changes'
oe_test_audit_rule_fetch_from_rule.sh: line 36: auditctl: command not found
+ CHECK_RESULT 1 0 0 'grep failed'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='grep failed'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'grep failed'
+ LOG_ERROR 'grep failed'
+ message='grep failed'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'grep failed'
Tue Sep 12 10:28:10 2023 - ERROR - grep failed
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_audit_rule_fetch_from_rule.sh line 37'
+ message='oe_test_audit_rule_fetch_from_rule.sh line 37'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_audit_rule_fetch_from_rule.sh line 37'
Tue Sep 12 10:28:10 2023 - ERROR - oe_test_audit_rule_fetch_from_rule.sh line 37
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Sep 12 10:28:10 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Sep 12 10:28:10 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Sep 12 10:28:10 2023 - INFO  - Start to restore the test environment.
+ auditctl -D
oe_test_audit_rule_fetch_from_rule.sh: line 44: auditctl: command not found
+ rm -rf /opt/test.rules
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Sep 12 10:28:10 2023 - INFO  - End to restore the test environment.
