+ source ../common_lib/fsio_lib.sh
++ source /root/mugen/libs/locallibs/common_lib.sh
+++ python3 --version
+++ '[' 0 -eq 0 ']'
+++ source /root/mugen/libs/locallibs/common_lib_python.sh
++ export 'FS_TYPE=ext3 ext4 xfs'
++ FS_TYPE='ext3 ext4 xfs'
++ export LANG=en_US.UTF-8
++ LANG=en_US.UTF-8
++ REMOVE_VG
++ vggroup=
++ [[ '' != '' ]]
+++ df -T
+++ grep test_vggroup
+++ awk '{print $7}'
++ mounted=
++ [[ '' != '' ]]
++ lsblk
++ grep test_vggroup
++ [[ 1 -eq 0 ]]
++ rm -rf /tmp/point120230912100421 /tmp/point220230912100421 /tmp/point320230912100421
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start environment preparation.'
+ message='Start environment preparation.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start environment preparation.'
Tue Sep 12 10:04:22 2023 - INFO  - Start environment preparation.
+ point_list=($(CREATE_FS "ext3 ext4 xfs"))
++ CREATE_FS 'ext3 ext4 xfs'
++ fs_type='ext3 ext4 xfs'
+++ date +%Y%m%d%H%M%S
++ cur_date=20230912100422
+++ CREATE_VG
++++ date +%Y%m%d%H%M%S
+++ cur_date=20230912100422
++++ lsblk
++++ grep disk
++++ awk '{print $1}'
++++ tail -n 1
+++ free_disk=vdt
+++ disk_name=/dev/vdt
+++ pvcreate /dev/vdt -f
+++ [[ 127 -eq 0 ]]
++++ pvcreate /dev/vdt
++++ grep test_vggroup
++++ cut -d '"' -f 4
+++ vggroup=
+++ printf
printf: usage: printf [-v var] format [arguments]
++ vggroup=
++ count=1
++ msg=' '
++ for fs in ${fs_type[@]}
++ lvname=test_lv120230912100422
++ point=/tmp/point120230912100422
++ lvcreate -n test_lv120230912100422 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext3 /dev//test_lv120230912100422
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv120230912100422 does not exist and no size was specified.
++ mkdir /tmp/point120230912100422
++ mount /dev//test_lv120230912100422 /tmp/point120230912100422
mount: /tmp/point120230912100422: special device /dev//test_lv120230912100422 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100422 '
++ count=2
++ for fs in ${fs_type[@]}
++ lvname=test_lv220230912100422
++ point=/tmp/point220230912100422
++ lvcreate -n test_lv220230912100422 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t ext4 /dev//test_lv220230912100422
mke2fs 1.47.0 (5-Feb-2023)
The file /dev//test_lv220230912100422 does not exist and no size was specified.
++ mkdir /tmp/point220230912100422
++ mount /dev//test_lv220230912100422 /tmp/point220230912100422
mount: /tmp/point220230912100422: special device /dev//test_lv220230912100422 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100422 /tmp/point220230912100422 '
++ count=3
++ for fs in ${fs_type[@]}
++ lvname=test_lv320230912100422
++ point=/tmp/point320230912100422
++ lvcreate -n test_lv320230912100422 -L 512M -y
../common_lib/fsio_lib.sh: line 107: lvcreate: command not found
++ mkfs -t xfs /dev//test_lv320230912100422
mkfs: failed to execute mkfs.xfs: No such file or directory
++ mkdir /tmp/point320230912100422
++ mount /dev//test_lv320230912100422 /tmp/point320230912100422
mount: /tmp/point320230912100422: special device /dev//test_lv320230912100422 does not exist.
       dmesg(1) may have more information after failed mount system call.
++ msg=' /tmp/point120230912100422 /tmp/point220230912100422 /tmp/point320230912100422 '
++ count=4
++ echo /tmp/point120230912100422 /tmp/point220230912100422 /tmp/point320230912100422
+ ext3_point=/tmp/point220230912100422
+ ext4_point=/tmp/point320230912100422
+ xfs_point=
+ echo 'test file ext3'
+ LOG_INFO 'End of environmental preparation!'
+ message='End of environmental preparation!'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End of environmental preparation!'
Tue Sep 12 10:04:22 2023 - INFO  - End of environmental preparation!
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Tue Sep 12 10:04:22 2023 - INFO  - Start to run test.
+ gzip -c /tmp/point220230912100422/testFile1
+ ls /tmp/point320230912100422
+ grep testFile1.gz
testFile1.gz
+ CHECK_RESULT 0 0 0 'Compress file by gzip in /tmp/point320230912100422 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Compress file by gzip in /tmp/point320230912100422 failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ gzip -dv /tmp/point320230912100422/testFile1.gz
/tmp/point320230912100422/testFile1.gz:	-13.3% -- replaced with /tmp/point320230912100422/testFile1
+ ls /tmp/point220230912100422
+ grep testFile2
testFile2
+ CHECK_RESULT 0 0 0 'Decompress gzip file in /tmp/point220230912100422 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Decompress gzip file in /tmp/point220230912100422 failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ gzip -c /tmp/point220230912100422/testFile1
+ ls
+ grep testFile1.gz
+ CHECK_RESULT 1 0 0 'Compress file by gzip in  failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Compress file by gzip in  failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Compress file by gzip in  failed.'
+ LOG_ERROR 'Compress file by gzip in  failed.'
+ message='Compress file by gzip in  failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Compress file by gzip in  failed.'
Tue Sep 12 10:04:22 2023 - ERROR - Compress file by gzip in  failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_gzip_overfs.sh line 41'
+ message='oe_test_FSIO_gzip_overfs.sh line 41'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_gzip_overfs.sh line 41'
Tue Sep 12 10:04:22 2023 - ERROR - oe_test_FSIO_gzip_overfs.sh line 41
+ '[' 0 -eq 1 ']'
+ return 0
+ gzip -dv /testFile1.gz
gzip: /testFile1 already exists;	not overwritten
+ ls /tmp/point220230912100422
+ grep testFile3
testFile3
+ CHECK_RESULT 0 0 0 'Decompress gzip file in /tmp/point220230912100422 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Decompress gzip file in /tmp/point220230912100422 failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ gzip -c /tmp/point320230912100422/testFile1
+ ls
+ grep testFile2.gz
+ CHECK_RESULT 1 0 0 'Compress file by gzip in  failed.'
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log='Compress file by gzip in  failed.'
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n 'Compress file by gzip in  failed.'
+ LOG_ERROR 'Compress file by gzip in  failed.'
+ message='Compress file by gzip in  failed.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'Compress file by gzip in  failed.'
Tue Sep 12 10:04:22 2023 - ERROR - Compress file by gzip in  failed.
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_FSIO_gzip_overfs.sh line 47'
+ message='oe_test_FSIO_gzip_overfs.sh line 47'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_FSIO_gzip_overfs.sh line 47'
Tue Sep 12 10:04:22 2023 - ERROR - oe_test_FSIO_gzip_overfs.sh line 47
+ '[' 0 -eq 1 ']'
+ return 0
+ gzip -dv /testFile2.gz
/testFile2.gz:	-13.3% -- replaced with /testFile2
+ ls /tmp/point320230912100422
+ grep testFile2
testFile2
+ CHECK_RESULT 0 0 0 'Decompress gzip file in /tmp/point320230912100422 failed.'
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log='Decompress gzip file in /tmp/point320230912100422 failed.'
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Tue Sep 12 10:04:22 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 2
+ test 2 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Tue Sep 12 10:04:22 2023 - ERROR - failed to execute the case.
+ exit 2
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Tue Sep 12 10:04:22 2023 - INFO  - Start to restore the test environment.
++ echo /tmp/point120230912100422 /tmp/point220230912100422 /tmp/point320230912100422
+ list='/tmp/point120230912100422 /tmp/point220230912100422 /tmp/point320230912100422'
+ REMOVE_FS '/tmp/point120230912100422 /tmp/point220230912100422 /tmp/point320230912100422'
+ point_list=($1)
++ seq 0 2
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point120230912100422
++ df -T
++ grep /tmp/point120230912100422
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point220230912100422
++ df -T
++ grep /tmp/point220230912100422
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ for i in $(seq 0 $((${#point_list[@]} - 1)))
+ tmp=/tmp/point320230912100422
++ df -T
++ grep /tmp/point320230912100422
++ awk '{print $1}'
+ lv=
+ [[ '' == '' ]]
+ continue
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Tue Sep 12 10:04:22 2023 - INFO  - End to restore the test environment.
