+ source /root/mugen/libs/locallibs/common_lib.sh
++ python3 --version
++ '[' 0 -eq 0 ']'
++ source /root/mugen/libs/locallibs/common_lib_python.sh
+ main
++ type -t post_test
+ '[' -n function ']'
+ trap post_test EXIT INT HUP TERM
+ rpm -qa
+ grep expect
++ type -t config_params
+ '[' -n '' ']'
++ type -t pre_test
+ '[' -n function ']'
+ pre_test
+ LOG_INFO 'Start to prepare the test environment.'
+ message='Start to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to prepare the test environment.'
Fri Sep 22 08:50:38 2023 - INFO  - Start to prepare the test environment.
+ DNF_INSTALL tuned
+ pkgs=tuned
+ node=1
+ '[' -z '' ']'
+ tmpfile=
++ python3 /root/mugen/libs/locallibs/rpm_manage.py install --pkgs tuned --node 1 --tempfile ''
Fri Sep 22 08:50:46 2023 - INFO  - pkgs:(tuned) is already installed
+ tmpfile2=
+ '[' -z '' ']'
+ tmpfile=
+ LOG_INFO 'End to prepare the test environment.'
+ message='End to prepare the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to prepare the test environment.'
Fri Sep 22 08:50:46 2023 - INFO  - End to prepare the test environment.
++ type -t run_test
+ '[' -n function ']'
+ run_test
+ LOG_INFO 'Start to run test.'
+ message='Start to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to run test.'
Fri Sep 22 08:50:47 2023 - INFO  - Start to run test.
+ systemctl enable --now tuned
Job for tuned.service failed because the control process exited with error code.
See "systemctl status tuned.service" and "journalctl -xeu tuned.service" for details.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_disk_tuned_disable.sh line 29'
+ message='oe_test_disk_tuned_disable.sh line 29'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_disk_tuned_disable.sh line 29'
Fri Sep 22 08:50:52 2023 - ERROR - oe_test_disk_tuned_disable.sh line 29
+ '[' 0 -eq 1 ']'
+ return 0
+ test -f /etc/systemd/system/multi-user.target.wants/tuned.service
+ systemctl status tuned
+ grep running
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_disk_tuned_disable.sh line 32'
+ message='oe_test_disk_tuned_disable.sh line 32'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_disk_tuned_disable.sh line 32'
Fri Sep 22 08:50:53 2023 - ERROR - oe_test_disk_tuned_disable.sh line 32
+ '[' 0 -eq 1 ']'
+ return 0
+ tuned-adm off
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/tuned/utils/global_config.py", line 44, in load_config
    with open(file_name) as f:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/etc/tuned/tuned-main.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/tuned-adm", line 50, in <module>
    config = GlobalConfig()
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/tuned/utils/global_config.py", line 15, in __init__
    self.load_config(file_name=config_file)
  File "/usr/lib/python3.11/site-packages/tuned/utils/global_config.py", line 59, in load_config
    raise TunedException("Global TuneD configuration file '%s' not found." % file_name)
tuned.exceptions.TunedException: Global TuneD configuration file '/etc/tuned/tuned-main.conf' not found.
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_disk_tuned_disable.sh line 34'
+ message='oe_test_disk_tuned_disable.sh line 34'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_disk_tuned_disable.sh line 34'
Fri Sep 22 08:50:55 2023 - ERROR - oe_test_disk_tuned_disable.sh line 34
+ '[' 0 -eq 1 ']'
+ return 0
+ systemctl disable --now tuned
Removed "/etc/systemd/system/multi-user.target.wants/tuned.service".
+ CHECK_RESULT 0
+ actual_result=0
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 0 ']'
+ '[' 0 -eq 0 ']'
+ test 0x '!=' 0x
+ return 0
+ test -f /etc/systemd/system/multi-user.target.wants/tuned.service
+ CHECK_RESULT 1 1
+ actual_result=1
+ expect_result=1
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 1x
+ return 0
+ systemctl status tuned
+ grep inactive
+ CHECK_RESULT 1
+ actual_result=1
+ expect_result=0
+ mode=0
+ error_log=
+ exit_mode=0
+ '[' -z 1 ']'
+ '[' 0 -eq 0 ']'
+ test 1x '!=' 0x
+ test -n ''
+ (( exec_result++ ))
+ LOG_ERROR 'oe_test_disk_tuned_disable.sh line 40'
+ message='oe_test_disk_tuned_disable.sh line 40'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'oe_test_disk_tuned_disable.sh line 40'
Fri Sep 22 08:50:59 2023 - ERROR - oe_test_disk_tuned_disable.sh line 40
+ '[' 0 -eq 1 ']'
+ return 0
+ LOG_INFO 'End to run test.'
+ message='End to run test.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to run test.'
Fri Sep 22 08:50:59 2023 - INFO  - End to run test.
+ CASE_RESULT 0
+ case_re=0
+ test -z 4
+ test 4 -gt 0
+ LOG_ERROR 'failed to execute the case.'
+ message='failed to execute the case.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level error --message 'failed to execute the case.'
Fri Sep 22 08:51:00 2023 - ERROR - failed to execute the case.
+ exit 4
+ post_test
+ LOG_INFO 'Start to restore the test environment.'
+ message='Start to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'Start to restore the test environment.'
Fri Sep 22 08:51:00 2023 - INFO  - Start to restore the test environment.
+ DNF_REMOVE
+ node=1
+ pkg_list=
+ mode=0
+ [[ -z '' ]]
+ [[ -z '' ]]
+ LOG_WARN 'no thing to do.'
+ message='no thing to do.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level warn --message 'no thing to do.'
Fri Sep 22 08:51:01 2023 - WARN  - no thing to do.
+ return 0
+ LOG_INFO 'End to restore the test environment.'
+ message='End to restore the test environment.'
+ python3 /root/mugen/libs/locallibs/mugen_log.py --level info --message 'End to restore the test environment.'
Fri Sep 22 08:51:01 2023 - INFO  - End to restore the test environment.
